apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-service-sa
  namespace: core-services

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: core-services
  name: deployment-service-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-service-rolebinding
  namespace: core-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-service-role
subjects:
- kind: ServiceAccount
  name: deployment-service-sa
  namespace: core-services


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  namespace: core-services
  labels:
    app: deployment-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deployment-service
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      serviceAccountName: deployment-service-sa
      containers:
      - name: deployment-service
        image: dubemezeagwu/deployment-service:v0.0.6
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: core-services
spec:
  selector:
    app: deployment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
