apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-service-sa
  namespace: core-services

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: core-services
  name: deployment-service-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-service-rolebinding
  namespace: core-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-service-role
subjects:
- kind: ServiceAccount
  name: deployment-service-sa
  namespace: core-services
